version: '3'
services:
  vault:
    image: 'vault'
    command: server
    cap_add:
      - IPC_LOCK
    ports:
      - "8202:8202"
    volumes:
      - "./config-pre-tls:/vault/config:ro"
      - "./data:/vault/file"
