version: '3'
services:
  vault:
    image: 'vault'
    command: server
    cap_add:
      - IPC_LOCK
    ports:
      - "8202:8202"
    environment:
      - VAULT_LOCAL_CONFIG=/vault-config/vault-no-tls.hcl
    volumes:
      - "./config:/vault-config:ro"
      - "./data:/vault/file"
