version: '3'
services:
  vault:
    image: 'vault'
    command: server
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - "./config:/vault/config"
      - "./data:/vault/file"
